version: "3.9"

services:
  server:
    build: .
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      GIN_MODE: release
    depends_on:
      - redis

  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data:
